version: "2"

services:
  create-react-app:
    build: ./create-react-app
    working_dir: /home/node/app
    ports:
      - 3100:3000
    volumes:
      - ../:/home/node/app

  node:
    image: node:8.7
    volumes:
      - ../:/app
    working_dir: /app
